name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  
  workflow_dispatch:
    inputs:
      myFirstInput:
        description: 'First Input'     
        required: true
        default: 'code to cloud!'
      mySecondInput:
        description: 'Second Input'  

jobs:
  Build:
    name: Test this Demo

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: Testing Manual Inputs
      run: |
        echo "First Input: ${{ github.event.inputs.myFirstInput }}"
        echo "Second Input: ${{ github.event.inputs.mySecondInput }}" 
